In [1]:
# 1. Setup & Configuration
import pandas as pd
import time
from institution_checker import run_pipeline, set_api_key
from name_matcher.pipeline import NameMatcher, NameMatcherConfig

# Configure API Key
set_api_key("sk-3f1dbbf2450e46ab9541dffba4f18ec6")

# Configure Name Matching
config = NameMatcherConfig(name_column="name", use_tqdm=True)
config.llm_token = "sk-3f1dbbf2450e46ab9541dffba4f18ec6"

print("✅ System initialized.")

C:\Users\setiawa\Documents\institution_checker\src\institution_checker\llm_processor.py:100: FutureWarning: Possible set difference at position 14
  DATE_RANGE_PATTERN = re.compile(r'\b(\d{4})\s*[---]\s*(\d{4})\b')

✅ System initialized.

## 2. Data Sampling (100 Names)
We select a mix of known Purdue laureates (VIPs) and random awardees to demonstrate accuracy.

In [2]:
# Load Source Data
source_path = r"E:\Ace\To be sorted\Purdue Trial Set HP Awardees 2024-10-23.xlsx"
try:
    df = pd.read_excel(source_path, dtype=str)
except FileNotFoundError:
    # Fallback if E: drive is not available
    print("⚠️ Source file not found. Generating synthetic data for demo.")
    df = pd.DataFrame({'name': [
        "John B. Fenn", "Ei-ichi Negishi", "Herbert C. Brown", "Akira Suzuki", 
        "Vernon L. Smith", "Ben R. Mottelson", "E. M. Purcell", "Julian Schwinger", 
        "Wolfgang Pauli"
    ] + [f"Random Person {i}" for i in range(91)]})

# Define VIPs (Known Purdue Connections)
vip_names = [
    "Akira Suzuki", "Ei-ichi Negishi", "Herbert C. Brown", 
    "John B. Fenn", "Vernon L. Smith", "Ben R. Mottelson", 
    "E. M. Purcell", "Julian Schwinger", "Wolfgang Pauli"
]

# 1. Select VIPs
vip_mask = df['name'].apply(lambda x: any(vip.lower() in str(x).lower() for vip in vip_names))
df_vips = df[vip_mask].copy()

# 2. Select Random Sample (to reach 100 total)
df_others = df[~vip_mask].copy()
remaining_count = 100 - len(df_vips)
df_random = df_others.sample(n=min(remaining_count, len(df_others)), random_state=42)

# 3. Combine
df_demo = pd.concat([df_vips, df_random]).drop_duplicates(subset=['name']).reset_index(drop=True)

print(f"📊 Demo Dataset Prepared:")
print(f"   - VIPs (Known): {len(df_vips)}")
print(f"   - Random Sample: {len(df_random)}")
print(f"   - Total: {len(df_demo)} names")
display(df_demo.head())

📊 Demo Dataset Prepared:
   - VIPs (Known): 24
   - Random Sample: 76
   - Total: 76 names

,in AcA,Purdue,mexclusive_conn,checked (blue),id,award,name,year,affiliation,govid,...,year elected,state,previous service,current service,discipline,related_links,note,position,subaward,fulltext
0,NaN,True,Postdoc,1,2230,Nobel Prize-Chemistry,Akira Suzuki,2010,NaN,248,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,False,True,Alumni,1,819,American Philosophical Society Membership,Ben R. Mottelson,2011,"The Niels Bohr Institute, University of Copen...",91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visiting Professor,NaN,NaN
2,False,True,Alumni,1,2023,NAS Members,E. M. Purcell,1951,Harvard University,222,...,Member (elected 1951),NaN,NaN,NaN,Scientific Discipline: Physics,http://www.nasonline.org/publications/biograph...,NaN,NaN,NaN,NaN
3,False,True,Faculty,1,101,American Academy of Arts and Sciences Member/F...,Ei-ichi Negishi,2011,NaN,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,False,True,Faculty,1,404,Priestley Medal,Herbert C. Brown,1981,Purdue University,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Professor Emeritus,NaN,NaN

## 3. Entity Resolution
Clustering similar names to ensure we don't process duplicates (e.g., "John Fenn" vs "J.B. Fenn").

In [3]:
print("🧩 Clustering names...")
matcher = NameMatcher(config)
result = matcher.cluster(df_demo)
df_clustered = result.dataframe

# Select Representatives
cluster_reps = df_clustered.groupby('cluster_label')['name'].first().reset_index()
cluster_reps.columns = ['cluster_label', 'representative_name']

# Ensure VIPs are the representatives for their clusters (for better search results)
for vip in vip_names:
    vip_rows = df_clustered[df_clustered['name'].str.contains(vip, case=False, na=False)]
    if not vip_rows.empty:
        cluster_label = vip_rows.iloc[0]['cluster_label']
        cluster_reps.loc[cluster_reps['cluster_label'] == cluster_label, 'representative_name'] = vip

names_to_check = cluster_reps['representative_name'].tolist()
print(f"✅ Reduced to {len(names_to_check)} unique clusters to verify.")

🧩 Clustering names...
--- Name Matcher Process Started (v6.8.8 Improved Canonical Name Selection) ---

1. Loading and preparing data...
   Loaded 76 names. Done in 0.00s
2. Vectorizing names for similarity scoring...
   Done in 0.00s
3. Generating candidate pairs via Blocking...
   Generated 4 candidate pairs from blocking.
   Done in 0.00s
4. Applying Stricter Cluster-Centric Filtering...

   Filtering Pairs: 100%|██████████| 4/4 [00:00<?, ?pair/s]

   Filter Stats: {'merged_expansion': 4}
   Done in 0.00s
5. Reviewing ambiguous pairs with LLM...
   Done in 0.00s
6. Finalizing cluster data structures...
   Done in 0.00s
7. Refining clusters by ejecting outliers...
   Found and ejected 0 outliers from clusters.
   Done in 0.00s
8. Assigning canonical names and saving results...

--- Results Summary ---
   - Total names processed: 76
   - Unique entities (clusters) found: 72

   --- Sample of Largest Clusters Found ---
   Cluster 1 (Size: 2): 'Edward Mills Purcell'
     - E. M. Purcell
     - Edward Mills Purcell
   Cluster 2 (Size: 2): 'Julian Seymour Schwinger'
     - Julian Schwinger
     - Julian Seymour Schwinger
   Cluster 3 (Size: 2): 'Harlan Fiske Stone'
     - Harlan F. Stone
     - Harlan Fiske Stone
   Cluster 4 (Size: 2): 'Armin Dale Kaiser'
     - A. Dale Kaiser
     - Armin Dale Kaiser
   Done in 0.00s

--- Name Matcher Process Finished in 0.02 seconds ---
✅ Reduced to 72 unique clusters to verify.

## 4. Verification Pipeline
Running the AI-driven search and verification process.

In [4]:
print(f"🚀 Starting verification for {len(names_to_check)} names...")
start_time = time.time()

# Run the pipeline
results = await run_pipeline(
    names_to_check, 
    batch_size=10,              # Efficient batch size
    use_enhanced_search=True,   # Deep search for accuracy
    dataset_profile="high_connection", # Conservative filtering
    use_dynamic_batching=True
)

elapsed = time.time() - start_time
print(f"🏁 Completed in {elapsed:.1f}s ({elapsed/len(names_to_check):.2f}s per name)")

🚀 Starting verification for 72 names...
[PIPELINE] Starting DYNAMIC BATCHING mode
[PIPELINE] Total: 72 names, Search batch: 10, LLM batch: 10
[PIPELINE] Using enhanced search, Dataset profile: high_connection

Processing search batches:   0%|          | 0/8 [00:00<?, ?batch/s]

[PIPELINE] ===== SEARCH BATCH 1/8 =====
[PIPELINE] Names: Akasha Gloria Hull, Akira Suzuki, Albert Warner Overhauser, Andrew J. Majda, A. Dale Kaiser, Ben R. Mottelson, Bob Hicok, Carl R. de Boor, Charles J. Arntzen, Chintamani Nagesa Ramachandra Rao
[SEARCH] Running parallel searches for 10 names (max 15 concurrent)...
[PROGRESS] Starting search for: Akasha Gloria Hull
[PROGRESS] Name: 'Akasha Gloria Hull' | Query: 'Akasha Gloria Hull "Purdue University"'
[PROGRESS] Starting search for: Akira Suzuki
[PROGRESS] Name: 'Akira Suzuki' | Query: 'Akira Suzuki "Purdue University"'
[PROGRESS] Starting search for: Albert Warner Overhauser
[PROGRESS] Name: 'Albert Warner Overhauser' | Query: 'Albert Warner Overhauser "Purdue University"'
[PROGRESS] Starting search for: Andrew J. Majda
[PROGRESS] Name: 'Andrew J. Majda' | Query: 'Andrew J. Majda "Purdue University"'
[PROGRESS] Starting search for: A. Dale Kaiser
[PROGRESS] Name: 'A. Dale Kaiser' | Query: 'A. Dale Kaiser "Purdue University"'
[PROGRESS] Starting search for: Ben R. Mottelson
[PROGRESS] Name: 'Ben R. Mottelson' | Query: 'Ben R. Mottelson "Purdue University"'
[PROGRESS] Starting search for: Bob Hicok
[PROGRESS] Name: 'Bob Hicok' | Query: 'Bob Hicok "Purdue University"'
[PROGRESS] Starting search for: Carl R. de Boor
[PROGRESS] Name: 'Carl R. de Boor' | Query: 'Carl R. de Boor "Purdue University"'
[PROGRESS] Starting search for: Charles J. Arntzen
[PROGRESS] Name: 'Charles J. Arntzen' | Query: 'Charles J. Arntzen "Purdue University"'
[PROGRESS] Starting search for: Chintamani Nagesa Ramachandra Rao
[PROGRESS] Name: 'Chintamani Nagesa Ramachandra Rao' | Query: 'Chintamani Nagesa Ramachandra Rao "Purdue University"'
[PROGRESS] Result sample: AkashaHull was born Gloria Theresa Thompson on December 6, 1944, in Shreveport,
[PROGRESS] Basic search returned 17 results with max_score=21, sufficient for analysis
[PROGRESS] Search completed for Akasha Gloria Hull in 6.9s, found 17 results
[PROGRESS] Result sample: WEST LAFAYETTE, Ind.
[PROGRESS] Basic search returned 15 results with max_score=22, sufficient for analysis
[PROGRESS] Search completed for Chintamani Nagesa Ramachandra Rao in 6.3s, found 15 results
[PROGRESS] Result sample: Kaiser received in 1950 his bachelor's degree from Purdue University and in 1955
[PROGRESS] Basic search returned 18 results with max_score=31, sufficient for analysis
[PROGRESS] Search completed for A. Dale Kaiser in 6.3s, found 18 results
[PROGRESS] Result sample: The participants in the Albert W. Overhauser Symposium at Purdue University, 21
[PROGRESS] Basic search returned 17 results with max_score=29, sufficient for analysis
[PROGRESS] Search completed for Albert Warner Overhauser in 6.4s, found 17 results
[PROGRESS] Result sample: MOTTELSON, BENR.MOTTELSON, BENR. (1926- ), U.S. and Danish physicist and Nobel l
[PROGRESS] Basic search returned 16 results with max_score=27, sufficient for analysis
[PROGRESS] Search completed for Ben R. Mottelson in 6.7s, found 16 results
[PROGRESS] Result sample: Department of Computer Science Technical Reports Least Squares Cubic Spline Appr
[PROGRESS] Basic search returned 4 results, few results, escalating to enhanced search...
[PROGRESS] Result sample: Career Born in East Chicago, Indiana, Majda received a B.S. degree in mathematic
[PROGRESS] Basic search returned 9 results with max_score=19, sufficient for analysis
[PROGRESS] Search completed for Andrew J. Majda in 6.9s, found 9 results
[PROGRESS] Result sample: BobHicok's most recent collection of poetry is Sex & Love &. His work has been a
[PROGRESS] Basic search returned 15 results with max_score=19, sufficient for analysis
[PROGRESS] Search completed for Bob Hicok in 7.3s, found 15 results
[PROGRESS] Result sample: Heck began the process in the late 1960s. Suzuki and Negishi (who both studied a
[PROGRESS] Basic search returned 16 results with max_score=31, sufficient for analysis
[PROGRESS] Search completed for Akira Suzuki in 9.3s, found 16 results
[PROGRESS] Result sample: He was awarded honorary doctorates from the University of Minnesota, Purdue Univ
[PROGRESS] Basic search returned 16 results with max_score=23, sufficient for analysis
[PROGRESS] Search completed for Charles J. Arntzen in 9.4s, found 16 results
[PROGRESS] Search completed for Carl R. de Boor in 44.0s, found 6 results
[SEARCH] Search succeeded for Akasha Gloria Hull: 17 results
[SEARCH] Search succeeded for Akira Suzuki: 16 results
[SEARCH] Search succeeded for Albert Warner Overhauser: 17 results
[SEARCH] Search succeeded for Andrew J. Majda: 9 results
[SEARCH] Search succeeded for A. Dale Kaiser: 18 results
[SEARCH] Search succeeded for Ben R. Mottelson: 16 results
[SEARCH] Search succeeded for Bob Hicok: 15 results
[SEARCH] Search succeeded for Carl R. de Boor: 6 results
[SEARCH] Search succeeded for Charles J. Arntzen: 16 results
[SEARCH] Search succeeded for Chintamani Nagesa Ramachandra Rao: 15 results
[SKIP-EVAL] Evaluating skip logic for 10 names (dataset_profile=high_connection)...
[ACCUM] Added Akasha Gloria Hull to LLM batch (accumulated: 1)
[ACCUM] Added Akira Suzuki to LLM batch (accumulated: 2)
[ACCUM] Added Albert Warner Overhauser to LLM batch (accumulated: 3)
[ACCUM] Added Andrew J. Majda to LLM batch (accumulated: 4)
[ACCUM] Added A. Dale Kaiser to LLM batch (accumulated: 5)
[ACCUM] Added Ben R. Mottelson to LLM batch (accumulated: 6)
[ACCUM] Added Bob Hicok to LLM batch (accumulated: 7)
[ACCUM] Added Carl R. de Boor to LLM batch (accumulated: 8)
[ACCUM] Added Charles J. Arntzen to LLM batch (accumulated: 9)
[ACCUM] Added Chintamani Nagesa Ramachandra Rao to LLM batch (accumulated: 10)
[SEARCH-BATCH] Completed in 44.8s - Skipped: 0, Accumulated: 10

[LLM-TRIGGER] Accumulated 10 names, triggering LLM batch...
[LLM-BATCH] Processing 10 names through LLM...
[PROGRESS] Starting LLM analysis for: Akasha Gloria Hull
[PROGRESS] Starting LLM analysis for: Akira Suzuki
[PROGRESS] Starting LLM analysis for: Albert Warner Overhauser
[PROGRESS] Starting LLM analysis for: Andrew J. Majda
[PROGRESS] Starting LLM analysis for: A. Dale Kaiser
[PROGRESS] Starting LLM analysis for: Ben R. Mottelson
[PROGRESS] Starting LLM analysis for: Bob Hicok
[PROGRESS] Starting LLM analysis for: Carl R. de Boor
[PROGRESS] Starting LLM analysis for: Charles J. Arntzen
[PROGRESS] Starting LLM analysis for: Chintamani Nagesa Ramachandra Rao
[PROGRESS] LLM analysis completed for A. Dale Kaiser in 5.3s
[PROGRESS] LLM analysis completed for Carl R. de Boor in 5.7s
[PROGRESS] LLM analysis completed for Ben R. Mottelson in 5.9s
[PROGRESS] LLM analysis completed for Andrew J. Majda in 6.3s
[PROGRESS] LLM analysis completed for Bob Hicok in 6.6s
[PROGRESS] LLM analysis completed for Albert Warner Overhauser in 6.8s
[PROGRESS] LLM analysis completed for Akasha Gloria Hull in 6.8s
[PROGRESS] LLM analysis completed for Charles J. Arntzen in 7.4s
[PROGRESS] LLM analysis completed for Chintamani Nagesa Ramachandra Rao in 7.7s
[PROGRESS] LLM analysis completed for Akira Suzuki in 9.2s
[LLM-BATCH] LLM succeeded for Akasha Gloria Hull
[LLM-BATCH] LLM succeeded for Akira Suzuki
[LLM-BATCH] LLM succeeded for Albert Warner Overhauser
[LLM-BATCH] LLM succeeded for Andrew J. Majda
[LLM-BATCH] LLM succeeded for A. Dale Kaiser
[LLM-BATCH] LLM succeeded for Ben R. Mottelson
[LLM-BATCH] LLM succeeded for Bob Hicok
[LLM-BATCH] LLM succeeded for Carl R. de Boor
[LLM-BATCH] LLM succeeded for Charles J. Arntzen
[LLM-BATCH] LLM succeeded for Chintamani Nagesa Ramachandra Rao
[LLM-BATCH] Batch completed in 9.2s
[LLM-TRIGGER] Processed LLM batch, 0 names still accumulated
[PIPELINE] Waiting 1s before next search batch...

[PIPELINE] ===== SEARCH BATCH 2/8 =====
[PIPELINE] Names: Chris Beard, Christopher L. Eisgruber, Clark Wissler, Daniel L. Hartl, David H. MacLennan, Dennis H. Klatt, E. M. Purcell, Ei-ichi Negishi, F. Kenneth Iverson, Fred I. Dretske
[SEARCH] Running parallel searches for 10 names (max 15 concurrent)...
[PROGRESS] Starting search for: Chris Beard
[PROGRESS] Name: 'Chris Beard' | Query: 'Chris Beard "Purdue University"'
[PROGRESS] Starting search for: Christopher L. Eisgruber
[PROGRESS] Name: 'Christopher L. Eisgruber' | Query: 'Christopher L. Eisgruber "Purdue University"'
[PROGRESS] Starting search for: Clark Wissler
[PROGRESS] Name: 'Clark Wissler' | Query: 'Clark Wissler "Purdue University"'
[PROGRESS] Starting search for: Daniel L. Hartl
[PROGRESS] Name: 'Daniel L. Hartl' | Query: 'Daniel L. Hartl "Purdue University"'
[PROGRESS] Starting search for: David H. MacLennan
[PROGRESS] Name: 'David H. MacLennan' | Query: 'David H. MacLennan "Purdue University"'
[PROGRESS] Starting search for: Dennis H. Klatt
[PROGRESS] Name: 'Dennis H. Klatt' | Query: 'Dennis H. Klatt "Purdue University"'
[PROGRESS] Starting search for: E. M. Purcell
[PROGRESS] Name: 'E. M. Purcell' | Query: 'E. M. Purcell "Purdue University"'
[PROGRESS] Starting search for: Ei-ichi Negishi
[PROGRESS] Name: 'Ei-ichi Negishi' | Query: 'Ei-ichi Negishi "Purdue University"'
[PROGRESS] Starting search for: F. Kenneth Iverson
[PROGRESS] Name: 'F. Kenneth Iverson' | Query: 'F. Kenneth Iverson "Purdue University"'
[PROGRESS] Starting search for: Fred I. Dretske
[PROGRESS] Name: 'Fred I. Dretske' | Query: 'Fred I. Dretske "Purdue University"'
[PROGRESS] Result sample: stackexchange.com https://math.stackexchange.com › questions
[PROGRESS] Basic search returned 11 results, low quality (max_score=2), escalating to enhanced search...
[PROGRESS] Result sample: wikipedia.org https://en.wikipedia.org › wiki › Dennis
[PROGRESS] Basic search returned 12 results, low quality (max_score=1), escalating to enhanced search...
[PROGRESS] Result sample: covers.com https://www.covers.com › boxing › david-benavidez-vs-anthony-yarde-pr
[PROGRESS] Basic search returned 3 results, few results, escalating to enhanced search...
[PROGRESS] Result sample: Born and raised in Taylorville, Illinois, Purcell received his BSEE in electrica
[PROGRESS] Basic search returned 17 results with max_score=27, sufficient for analysis
[PROGRESS] Search completed for E. M. Purcell in 4.7s, found 17 results
[PROGRESS] Result sample: DanielHartlDanielL.Hartl is Higgins Professor of Biology in the Department of Or
[PROGRESS] Basic search returned 17 results with max_score=20, sufficient for analysis
[PROGRESS] Search completed for Daniel L. Hartl in 4.7s, found 17 results
[PROGRESS] Result sample: Clark David Wissler was born in Cambridge City, Indiana on September 18, 1870, t
[PROGRESS] Basic search returned 15 results with max_score=20, sufficient for analysis
[PROGRESS] Search completed for Clark Wissler in 4.8s, found 15 results
[PROGRESS] Result sample: F.KennethIverson received a B.S. degree in aeronautical engineering from Cornell
[PROGRESS] Basic search returned 10 results with max_score=26, sufficient for analysis
[PROGRESS] Search completed for F. Kenneth Iverson in 5.1s, found 10 results
[PROGRESS] Result sample: The child of German immigrants who met as graduate students at Purdue University
[PROGRESS] Basic search returned 13 results with max_score=18, sufficient for analysis
[PROGRESS] Search completed for Christopher L. Eisgruber in 5.4s, found 13 results
[PROGRESS] Result sample: Staff Directory Scroll down to see a directory for our department. Admission Que
[PROGRESS] Basic search returned 4 results, few results, escalating to enhanced search...
[PROGRESS] Result sample: Born to Frederick and Hattie Dretske, Dretske first planned to be an engineer, a
[PROGRESS] Basic search returned 18 results with max_score=14, sufficient for analysis
[PROGRESS] Search completed for Fred I. Dretske in 8.6s, found 18 results
[PROGRESS] Search completed for Ei-ichi Negishi in 38.7s, found 9 results
[PROGRESS] Search completed for Dennis H. Klatt in 39.2s, found 9 results
[PROGRESS] Search completed for Chris Beard in 42.6s, found 6 results
[PROGRESS] Search completed for David H. MacLennan in 43.1s, found 6 results
[SEARCH] Search succeeded for Chris Beard: 6 results
[SEARCH] Search succeeded for Christopher L. Eisgruber: 13 results
[SEARCH] Search succeeded for Clark Wissler: 15 results
[SEARCH] Search succeeded for Daniel L. Hartl: 17 results
[SEARCH] Search succeeded for David H. MacLennan: 6 results
[SEARCH] Search succeeded for Dennis H. Klatt: 9 results
[SEARCH] Search succeeded for E. M. Purcell: 17 results
[SEARCH] Search succeeded for Ei-ichi Negishi: 9 results
[SEARCH] Search succeeded for F. Kenneth Iverson: 10 results
[SEARCH] Search succeeded for Fred I. Dretske: 18 results
[SKIP-EVAL] Evaluating skip logic for 10 names (dataset_profile=high_connection)...
[ACCUM] Added Chris Beard to LLM batch (accumulated: 1)
[ACCUM] Added Christopher L. Eisgruber to LLM batch (accumulated: 2)
[ACCUM] Added Clark Wissler to LLM batch (accumulated: 3)
[ACCUM] Added Daniel L. Hartl to LLM batch (accumulated: 4)
[ACCUM] Added David H. MacLennan to LLM batch (accumulated: 5)
[ACCUM] Added Dennis H. Klatt to LLM batch (accumulated: 6)
[ACCUM] Added E. M. Purcell to LLM batch (accumulated: 7)
[SKIP] Skipped: Ei-ichi Negishi - Heuristic triage: no meaningful evidence (signal score 0, authority score 0)
[ACCUM] Added F. Kenneth Iverson to LLM batch (accumulated: 8)
[ACCUM] Added Fred I. Dretske to LLM batch (accumulated: 9)
[SEARCH-BATCH] Completed in 43.1s - Skipped: 1, Accumulated: 9
[PIPELINE] Waiting 1s before next search batch...

[PIPELINE] ===== SEARCH BATCH 3/8 =====
[PIPELINE] Names: Fred W. McLafferty, Fritz Leonhardt, George Andrew Olah, George Andrew Reisner, George Engelmann, George R. Wodicka, H. A. Bethe, Harlan F. Stone, Harry Beevers, Herbert C. Brown
[SEARCH] Running parallel searches for 10 names (max 15 concurrent)...
[PROGRESS] Starting search for: Fred W. McLafferty
[PROGRESS] Name: 'Fred W. McLafferty' | Query: 'Fred W. McLafferty "Purdue University"'
[PROGRESS] Starting search for: Fritz Leonhardt
[PROGRESS] Name: 'Fritz Leonhardt' | Query: 'Fritz Leonhardt "Purdue University"'
[PROGRESS] Starting search for: George Andrew Olah
[PROGRESS] Name: 'George Andrew Olah' | Query: 'George Andrew Olah "Purdue University"'
[PROGRESS] Starting search for: George Andrew Reisner
[PROGRESS] Name: 'George Andrew Reisner' | Query: 'George Andrew Reisner "Purdue University"'
[PROGRESS] Starting search for: George Engelmann
[PROGRESS] Name: 'George Engelmann' | Query: 'George Engelmann "Purdue University"'
[PROGRESS] Starting search for: George R. Wodicka
[PROGRESS] Name: 'George R. Wodicka' | Query: 'George R. Wodicka "Purdue University"'
[PROGRESS] Starting search for: H. A. Bethe
[PROGRESS] Name: 'H. A. Bethe' | Query: 'H. A. Bethe "Purdue University"'
[PROGRESS] Starting search for: Harlan F. Stone
[PROGRESS] Name: 'Harlan F. Stone' | Query: 'Harlan F. Stone "Purdue University"'
[PROGRESS] Starting search for: Harry Beevers
[PROGRESS] Name: 'Harry Beevers' | Query: 'Harry Beevers "Purdue University"'
[PROGRESS] Starting search for: Herbert C. Brown
[PROGRESS] Name: 'Herbert C. Brown' | Query: 'Herbert C. Brown "Purdue University"'
[PROGRESS] Result sample: stackoverflow.com https://stackoverflow.com › questions
[PROGRESS] Basic search returned 11 results, low quality (max_score=1), escalating to enhanced search...
[PROGRESS] Result sample: Herbert C. Brown: 1979 Nobel Prize in Chemistry
[PROGRESS] Basic search returned 20 results with max_score=24, sufficient for analysis
[PROGRESS] Search completed for Herbert C. Brown in 4.1s, found 20 results
[PROGRESS] Result sample: wikipedia.org https:// en.wikipedia.org › wiki › George_(given_name )
[PROGRESS] Basic search returned 10 results, low quality (max_score=1), escalating to enhanced search...
[PROGRESS] Result sample: wikipedia.org https://en.m.wikipedia.org › wiki › Prince_Harry,_Duke_of_Sussex
[PROGRESS] Basic search returned 11 results, low quality (max_score=1), escalating to enhanced search...
[PROGRESS] Result sample: "The Nonclassical Cation: A Classic Case of Conflict," written by Mark Peplow de
[PROGRESS] Basic search returned 13 results with max_score=31, sufficient for analysis
[PROGRESS] Search completed for George Andrew Olah in 5.3s, found 13 results
[PROGRESS] Result sample: The Purdue Alumnus Established 1912 MEMBER OF THE AMERICAN ALUMNI COUNCIL Vol. X
[PROGRESS] Basic search returned 13 results with max_score=10, sufficient for analysis
[PROGRESS] Search completed for George Engelmann in 5.5s, found 13 results
[PROGRESS] Result sample: GeorgeAndrewReisner (November 5, 1867
[PROGRESS] Basic search returned 17 results with max_score=16, sufficient for analysis
[PROGRESS] Search completed for George Andrew Reisner in 8.3s, found 17 results
[PROGRESS] Result sample: In 1900, Winthrop Stone became President of Purdue University. In the fall of th
[PROGRESS] Basic search returned 14 results with max_score=15, sufficient for analysis
[PROGRESS] Search completed for Harlan F. Stone in 10.3s, found 14 results
[PROGRESS] Result sample: BY BEN GERWICK FRITZLEONHARDT, professor and former rector (president) of Stuttg
[PROGRESS] Basic search returned 16 results with max_score=25, sufficient for analysis
[PROGRESS] Search completed for Fritz Leonhardt in 12.3s, found 16 results
[PROGRESS] Result sample: He is most noted for the discovery of what is now come to be known as the McLaff
[PROGRESS] Basic search returned 13 results with max_score=30, sufficient for analysis
[PROGRESS] Search completed for Fred W. McLafferty in 12.9s, found 13 results
[PROGRESS] Search completed for H. A. Bethe in 37.9s, found 9 results
[PROGRESS] Search completed for George R. Wodicka in 40.3s, found 9 results
[PROGRESS] Search completed for Harry Beevers in 40.4s, found 9 results
[SEARCH] Search succeeded for Fred W. McLafferty: 13 results
[SEARCH] Search succeeded for Fritz Leonhardt: 16 results
[SEARCH] Search succeeded for George Andrew Olah: 13 results
[SEARCH] Search succeeded for George Andrew Reisner: 17 results
[SEARCH] Search succeeded for George Engelmann: 13 results
[SEARCH] Search succeeded for George R. Wodicka: 9 results
[SEARCH] Search succeeded for H. A. Bethe: 9 results
[SEARCH] Search succeeded for Harlan F. Stone: 14 results
[SEARCH] Search succeeded for Harry Beevers: 9 results
[SEARCH] Search succeeded for Herbert C. Brown: 20 results
[SKIP-EVAL] Evaluating skip logic for 10 names (dataset_profile=high_connection)...
[ACCUM] Added Fred W. McLafferty to LLM batch (accumulated: 10)
[ACCUM] Added Fritz Leonhardt to LLM batch (accumulated: 11)
[ACCUM] Added George Andrew Olah to LLM batch (accumulated: 12)
[ACCUM] Added George Andrew Reisner to LLM batch (accumulated: 13)
[ACCUM] Added George Engelmann to LLM batch (accumulated: 14)
[ACCUM] Added George R. Wodicka to LLM batch (accumulated: 15)
[SKIP] Skipped: H. A. Bethe - Heuristic triage: no meaningful evidence (signal score 0, authority score 0)
[ACCUM] Added Harlan F. Stone to LLM batch (accumulated: 16)
[ACCUM] Added Harry Beevers to LLM batch (accumulated: 17)
[ACCUM] Added Herbert C. Brown to LLM batch (accumulated: 18)
[SEARCH-BATCH] Completed in 40.4s - Skipped: 1, Accumulated: 9

[LLM-TRIGGER] Accumulated 18 names, triggering LLM batch...
[LLM-BATCH] Processing 10 names through LLM...
[PROGRESS] Starting LLM analysis for: Chris Beard
[PROGRESS] Starting LLM analysis for: Christopher L. Eisgruber
[PROGRESS] Starting LLM analysis for: Clark Wissler
[PROGRESS] Starting LLM analysis for: Daniel L. Hartl
[PROGRESS] Starting LLM analysis for: David H. MacLennan
[PROGRESS] Starting LLM analysis for: Dennis H. Klatt
[PROGRESS] Starting LLM analysis for: E. M. Purcell
[PROGRESS] Starting LLM analysis for: F. Kenneth Iverson
[PROGRESS] Starting LLM analysis for: Fred I. Dretske
[PROGRESS] Starting LLM analysis for: Fred W. McLafferty
[PROGRESS] LLM analysis completed for Chris Beard in 5.3s
[PROGRESS] LLM analysis completed for Clark Wissler in 5.5s
[PROGRESS] LLM analysis completed for David H. MacLennan in 5.6s
[PROGRESS] LLM analysis completed for Fred I. Dretske in 5.6s

## 5. Results & Analysis

In [5]:
# Map results back to clusters
results_map = {name: res for name, res in zip(names_to_check, results)}

# Add results to dataframe
df_clustered['verdict'] = df_clustered['cluster_label'].map(lambda x: results_map.get(cluster_reps.set_index('cluster_label').loc[x, 'representative_name'], {}).get('verdict'))
df_clustered['institution'] = df_clustered['cluster_label'].map(lambda x: results_map.get(cluster_reps.set_index('cluster_label').loc[x, 'representative_name'], {}).get('institution'))
df_clustered['confidence'] = df_clustered['cluster_label'].map(lambda x: results_map.get(cluster_reps.set_index('cluster_label').loc[x, 'representative_name'], {}).get('confidence'))
df_clustered['evidence'] = df_clustered['cluster_label'].map(lambda x: results_map.get(cluster_reps.set_index('cluster_label').loc[x, 'representative_name'], {}).get('summary'))

# Identify Purdue Connections
def is_purdue_connected(row):
    inst = str(row.get('institution', '')).lower()
    return row['verdict'] == 'connected' and ('purdue' in inst)

df_clustered['is_connected'] = df_clustered.apply(is_purdue_connected, axis=1)

# Display Summary
connected_df = df_clustered[df_clustered['is_connected'] == True]

print(f"🏆 RESULTS SUMMARY")
print("="*60)
print(f"Total Analyzed: {len(df_clustered)}")
print(f"Confirmed Connections: {len(connected_df)}")
print(f"Connection Rate: {(len(connected_df)/len(df_clustered))*100:.1f}%")

print("\n🔍 CONFIRMED CONNECTIONS:")
display(connected_df[['name', 'verdict', 'confidence', 'evidence']])

# Export
df_clustered.to_excel("demo_results_100.xlsx", index=False)
print("\n💾 Results exported to 'demo_results_100.xlsx'")

🏆 RESULTS SUMMARY
============================================================
Total Analyzed: 76
Confirmed Connections: 40
Connection Rate: 52.6%

🔍 CONFIRMED CONNECTIONS:

,name,verdict,confidence,evidence
0,Akira Suzuki,connected,medium,Akira Suzuki was a postdoctoral fellow at Purd...
1,Ben R. Mottelson,connected,high,Ben R. Mottelson earned a Bachelor of Science ...
2,E. M. Purcell,connected,medium,E. M. Purcell earned a Bachelor of Science in ...
4,Herbert C. Brown,connected,high,Herbert C. Brown was a professor at Purdue Uni...
6,Julian Schwinger,connected,medium,Julian Schwinger served as an instructor (facu...
7,Vernon L. Smith,connected,high,Vernon L. Smith served as a full professor at ...
8,Leah H. Jamieson,connected,high,Leah H. Jamieson currently holds a faculty pos...
10,Daniel L. Hartl,connected,high,Daniel L. Hartl previously served as a faculty...
11,Michael Friedman,connected,high,Michael (Elliot) Friedman is a current profess...
15,Ronald R. Breaker,connected,high,Ronald R. Breaker earned his Ph.D. in Biochemi...
16,Edward Mills Purcell,connected,medium,E. M. Purcell earned a Bachelor of Science in ...
19,Charles J. Arntzen,connected,medium,Charles J. Arntzen earned a Ph.D. from Purdue ...
20,Jeffrey L. Bennetzen,connected,high,Jeffrey L. Bennetzen held faculty positions at...
23,Mitchell E. Daniels,connected,high,Mitch Daniels was President of Purdue Universi...
26,William L. Rowe,connected,medium,William L. Rowe served as a faculty member (pr...
28,Jean FranÃ§ois Treves,connected,high,He held a faculty position at Purdue Universit...
30,A. Dale Kaiser,connected,high,A. Dale Kaiser earned a B.S. from Purdue Unive...
34,Bob Hicok,connected,high,Bob Hicok holds a current faculty position as ...
35,Yitang Zhang,connected,high,Yitang Zhang earned his Ph.D. from Purdue Univ...
37,Andrew J. Majda,connected,high,Andrew J. Majda earned a Bachelor of Science d...
38,Fred I. Dretske,connected,medium,Fred I. Dretske earned a bachelor's degree in ...
39,Clark Wissler,connected,medium,Clark Wissler attended Purdue University as a ...
44,Rakesh Agrawal,connected,high,Rakesh Agrawal is a current distinguished prof...
46,Leonard Gillman,connected,medium,Leonard Gillman held a faculty position (instr...
49,Albert Warner Overhauser,connected,medium,Albert Warner Overhauser was a faculty member ...
51,Akasha Gloria Hull,connected,medium,Akasha Gloria Hull earned both a master's and ...
55,Fritz Leonhardt,connected,medium,Fritz Leonhardt attended Purdue University for...
56,Chintamani Nagesa Ramachandra Rao,connected,high,C.N.R. Rao earned a PhD from Purdue University...
57,George Andrew Reisner,connected,low,George Andrew Reisner was a past staff member ...
59,Herbert J. Muller,connected,high,Herbert J. Muller was a faculty member (Profes...
60,Wayne Buckles Nottingham,connected,high,Wayne Buckles Nottingham earned a Bachelor of ...
62,Nicholas A. Peppas,connected,high,Nicholas A. Peppas holds a distinguished profe...
65,James O. Berger,connected,high,James O. Berger served as a faculty member in ...
67,Julian Seymour Schwinger,connected,medium,Julian Schwinger served as an instructor (facu...
70,Armin Dale Kaiser,connected,high,A. Dale Kaiser earned a B.S. from Purdue Unive...
71,F. Kenneth Iverson,connected,medium,F. Kenneth Iverson earned a master's degree in...
72,Thomas S. Huang,connected,high,Thomas S. Huang was a professor at Purdue Univ...
73,Fred W. McLafferty,connected,medium,Fred W. McLafferty held a faculty position at ...
74,Loren Graham,connected,high,Loren Graham earned a Bachelor of Science in c...
75,Lee Grodzins,connected,medium,Lee Grodzins earned a Ph.D. from Purdue Univer...

💾 Results exported to 'demo_results_100.xlsx'

## 6. Appendix: Detailed Process Walkthrough (Example)
To understand the "black box" of the verification pipeline, here is a step-by-step execution for a single known connection (**Herbert C. Brown**).

In [6]:
import json
from institution_checker.main import process_name_search, process_name_llm
from institution_checker.search import _build_strategies
from institution_checker.llm_processor import _build_prompt

# Select a clear True Positive example
demo_name = "Herbert C. Brown"
institution = "Purdue University"

print(f"🔬 DETAILED WALKTHROUGH: {demo_name}")
print("="*60)

# 1. Query Generation
print(f"\n1️⃣  GENERATED SEARCH QUERIES:")
# We simulate the strategy generation to show what queries are used
strategies = _build_strategies(demo_name, institution, 5)
for s in strategies:
    print(f"   - [{s.name}]: {s.query}")

# 2. Search Execution
print(f"\n2️⃣  EXECUTING SEARCH (Live)...")
# We use the internal function to get raw results
_, search_results = await process_name_search(demo_name, use_enhanced_search=True)

print(f"   Found {len(search_results)} results. Top 3 examples:")
for i, res in enumerate(search_results[:3]):
    print(f"   {i+1}. {res['title']}")
    print(f"      {res['url']}")
    print(f"      Snippet: {res['snippet'][:120]}...")

# 3. LLM Prompt Construction
print(f"\n3️⃣  CONSTRUCTING LLM PROMPT:")
prompt = _build_prompt(demo_name, institution, search_results)
print(f"   [System]: You are an evidence-driven verifier...")
print(f"   [User]: ...Search findings:")
# Show a slice of the findings part of the prompt
start_marker = "Search findings:"
findings_start = prompt.find(start_marker)
if findings_start != -1:
    print(f"   {prompt[findings_start:findings_start+500]}...")
    print("   (...remaining results...)")

# 4. LLM Analysis
print(f"\n4️⃣  LLM DECISION:")
decision = await process_name_llm(demo_name, search_results)
print(json.dumps(decision, indent=2))

🔬 DETAILED WALKTHROUGH: Herbert C. Brown
============================================================

1️⃣  GENERATED SEARCH QUERIES:
   - [name_institution_combined]: "Herbert C. Brown" "Purdue University"
   - [explicit_connection]: "Herbert C. Brown" "Purdue University" ("professor at" OR "faculty" OR "graduated from" OR "degree from" OR "alumnus" OR "worked at" OR "postdoc" OR "post-doc")
   - [education]: "Herbert C. Brown" "Purdue University" ("degree" OR "graduated" OR "alumni" OR "PhD" OR "bachelor")
   - [directory]: "Herbert C. Brown" "Purdue University" site:purdue.edu ("faculty" OR "staff" OR "directory")

2️⃣  EXECUTING SEARCH (Live)...
[PROGRESS] Starting search for: Herbert C. Brown
[PROGRESS] Name: 'Herbert C. Brown' | Query: 'Herbert C. Brown "Purdue University"'
[PROGRESS] Result sample: Herbert C. Brown: 1979 Nobel Prize in Chemistry
[PROGRESS] Basic search returned 20 results with max_score=24, sufficient for analysis
[PROGRESS] Search completed for Herbert C. Brown in 4.8s, found 20 results
   Found 20 results. Top 3 examples:
   1. Herbert C. Brown: 1979 Nobel Prize in Chemistry
      https://www.chem.purdue.edu/hcbrown
      Snippet: Purdue University...
   2. The HerbertC.Brown Laboratory of Chemistry was named after him on Purdue University's campus. He was an honorary member of the International Academy of Science, Munich.
      https://en.wikipedia.org/wiki/Herbert_C._Brown
      Snippet: ...
   3. HerbertC.Brown Nobel Prize in Chemistry 1979 Born: 22 May 1912, London, United Kingdom Died: 19 December 2004, Lafayette, IN, USA Affiliation at the time of the award: Purdue University, West Lafayette, IN, USA Prize motivation: "for their development of the use of boron- and phosphorus-containing compounds, respectively, into important reagents in organic synthesis" Prize share: 1/2
      https://www.nobelprize.org/prizes/chemistry/1979/brown/facts
      Snippet: ...

3️⃣  CONSTRUCTING LLM PROMPT:
   [System]: You are an evidence-driven verifier...
   [User]: ...Search findings:
   Search findings:
1. Title: #1 Herbert C. Brown: 1979 Nobel Prize in Chemistry
   Snippet: Purdue University
   Excerpt: Herbert C. Brown: 1979 Nobel Prize in Chemistry - James Tarpo Jr. and Margaret Tarpo Department of Chemistry - Purdue University Skip to main content Home Herbert C. Brown Herbert C. Brown: 1979 Nobel Prize in Chemistry Herbert C. Brown: 1979 Nobel Prize in Chemistry Herbert C. Brown (1912-2004)...
   URL: https://www.chem.purdue.edu/hcbrown
2. Title: #4 The HerbertC.Brown Labo...
   (...remaining results...)

4️⃣  LLM DECISION:
[PROGRESS] Starting LLM analysis for: Herbert C. Brown
[PROGRESS] LLM analysis completed for Herbert C. Brown in 3.0s
{
  "name": "Herbert C. Brown",
  "institution": "Purdue University",
  "verdict": "connected",
  "connected": "Y",
  "relationship_type": "Faculty",
  "relationship_timeframe": "past",
  "verification_detail": "The Nobel Prize facts page states: \"Affiliation at the time of the award: Purdue University, West Lafayette, IN, USA\" and the Purdue archives describe him as a \"former Purdue University professor.\"",
  "summary": "Herbert C. Brown was a professor at Purdue University (faculty), a past affiliation.",
  "primary_source": "https://www.nobelprize.org/prizes/chemistry/1979/brown/facts",
  "confidence": "high",
  "verification_status": "verified",
  "temporal_context": "Affiliation noted in 1979 (award year); described as former professor after his death in 2004",
  "connection_type": "Faculty",
  "connection_detail": "The Nobel Prize facts page states: \"Affiliation at the time of the award: Purdue University, West Lafayette, IN, USA\" and the Purdue archives describe him as a \"former Purdue University professor.\"",
  "current_or_past": "past",
  "supporting_url": "https://www.nobelprize.org/prizes/chemistry/1979/brown/facts",
  "temporal_evidence": "Affiliation noted in 1979 (award year); described as former professor after his death in 2004"
}

## 7. Simplified Usage
While the appendix above shows the internal mechanics, the actual usage for a single name is just one line of code.

In [ ]:

import institution_checker

# Configure the target institution
config.INSTITUTION = "Purdue University"

# Find connection for Name and Institution
result = await process_name("Herbert C. Brown", use_enhanced_search=True)

print(f"Name: {result['name']}")
print(f"Verdict: {result['verdict']}")
print(f"Evidence: {result['summary']}")

[PROGRESS] Starting search for: Herbert C. Brown
[PROGRESS] Name: 'Herbert C. Brown' | Query: 'Herbert C. Brown "Purdue University"'
[PROGRESS] Result sample: Herbert C. Brown: 1979 Nobel Prize in Chemistry
[PROGRESS] Basic search returned 20 results with max_score=24, sufficient for analysis
[PROGRESS] Search completed for Herbert C. Brown in 2.0s, found 20 results
[PROGRESS] Starting LLM analysis for: Herbert C. Brown
[PROGRESS] LLM analysis completed for Herbert C. Brown in 3.3s
Name: Herbert C. Brown
Verdict: connected
Evidence: Herbert C. Brown was a professor at Purdue University (affiliated during his 1979 Nobel Prize), a past faculty relationship.